# Generated by Django 3.2.3 on 2021-05-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westarbucks1', '0002_auto_20210523_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
